const SOCKET_CONNECTION_TIMEOUT = 10000;
const SOCKET_RECONNECTION_ATTEMPTS = 5;
const SOCKET_RECONNECTION_DELAY = 1000;
const SOCKET_RECONNECTION_DELAY_MAX = 5000;

const SOCKET_EVENTS = {
    START_COLLABORATION: "startCollaboration",
    ADD_COLLABORATOR: "addCollaborator",
    REMOVE_COLLABORATOR: "removeCollaborator",
    GET_UPDATE: "getCanvas",
    SEND_UPDATE: "sendCanvas",
};

export {
    SOCKET_CONNECTION_TIMEOUT,
    SOCKET_RECONNECTION_ATTEMPTS,
    SOCKET_RECONNECTION_DELAY,
    SOCKET_RECONNECTION_DELAY_MAX,
    SOCKET_EVENTS,
};
